import DependencyTree
num=0
tree=DependencyTree.DependencyTree()
if num==1:#who did you send the letter to ?
	tree.add(7,'NMOD')
	tree.add(0,'ROOT')
	tree.add(2,'SUBJ')
	tree.add(2,'VG')
	tree.add(6,'DET')
	tree.add(4,'OBJ1')
	tree.add(4,'OBJ2')
	tree.add(2,'P')
elif num==2:#a hearing is scheduled on the issue today .
	tree.add(2,'DET')
	tree.add(3,'SBJ')
	tree.add(0,'ROOT')
	tree.add(3,'VG')
	tree.add(2,'NMOD')
	tree.add(7,'DET')
	tree.add(5,'PC')
	tree.add(4,'ADV')
	tree.add(3,'P')
elif num==3:#chun jin de hai shi K jin de ?
	tree.add(5,'eSelf')
	tree.add(1,'mAux')
	tree.add(0,'ROOT')
	tree.add(5,'Feat')
	tree.add(3,'Clas')
	tree.add(5,'mAux')
	tree.add(6,'p')
elif num==4:#xiao yu qiao qiao de ba tou lu chu shui mian 
	tree.add(2,'Feat')
	tree.add(6,'Poss')
	tree.add(7,'Mann')
	tree.add(3,'mAux')
	tree.add(6,'mPrep')
	tree.add(7,'Exp')
	tree.add(0,'ROOT')
	tree.add(7,'Loc')
elif num==5:#ta men shi yong bu tong cai liao zuo de, bai yun shi , xiao deng .
	tree.add(6,'Prod')
	tree.add(6,'mMod')
	tree.add(5,'mPrep')
	tree.add(5,'Feat')
	tree.add(6,'Malt')
	tree.add(0,'ROOT')
	tree.add(6,'mAux')
	tree.add(6,'P')
	tree.add(5,'eRect')
	tree.add(9,'P')
	tree.add(9,'eCoo')
	tree.add(11,'mMaj')
	tree.add(11,'P')
elif num==6:#yin xing shu, da xiong mao , ke xue jia ba ta men jiao zuo "huo hua shi".
	tree.add(2,'Feat')
	tree.add(8,'eEqu')
	tree.add(2,'P')
	tree.add(2,'eCoo')
	tree.add(4,'P')
	tree.add(9,'Agt')
	tree.add(8,'mPrep')
	tree.add(9,'Pat')
	tree.add(0,'ROOT')
	tree.add(9,'P')
	tree.add(9,'Clas')
	tree.add(9,'P')
	tree.add(9,'P')
tree.print_tree()
print tree.get_projective_order()
tree.get_mpc()